### PR TITLE
add Go_fibonacci.go

### PR DESCRIPTION
**Pull request by CozyDoomer**
Go implementation of fibonacci sequence similar to the existing implementation in C

I also added Go to language list in Languages.md, please tell me if that's not intended

### CODE REVIEW

**Comment by fharookshaik** [comment]
Hey @CozyDoomer, Thanks for your enormous contribution. I appreciate your sincere effort. I've reviewed your code and it's working fine. But I've encountered some small errors regarding indentation etc. and those were reported by Codacy bot. Resolving these errors will improve your code writing skills . Comment if you face any issues.

You're just one step away.

Happy Coding!!
Happy Contributing!!

**Review by fharookshaik — CHANGES_REQUESTED** [review]
necessary requests have been commented before.

Happy Coding!!
Happy Contributing!!

**Comment by CozyDoomer** [comment]
Great @fharookshaik thanks for the guidance!

**Comment by fharookshaik** [comment]
Happy by hearing that @CozyDoomer

**Comment by CozyDoomer** [comment]
Hey @fharookshaik, the remaining failing check is in Languages.md
not sure if I should fix this here as I used the same formatting as the existing list points

Please tell me if I should or if that's a different PR

**Comment by fharookshaik** [comment]
Don't focus on the Languages.md Just try modifying the code.

Thank You

**Pull request merged**
