### PR TITLE
added fibonacci series coded in bash

### PR DESCRIPTION
**Pull request by jeremynac**
Hello, this is the fibonacci series coded in bash.

### CODE REVIEW

**Comment by jeremynac** [comment]
Hi, i'm not sure why my code failed the checks. Anyone has an idea?
Great project btw!

**Comment by fharookshaik** [comment]
Hey @jeremynac . Great to see that you're contributing. Thanks for your effort. Please provide the working code output screenshot.

**Comment by fharookshaik** [comment]
And don't mind with the errors given by Greetings.

**Comment by jeremynac** [comment]
image
Thanks,
this is a screenshot of fibonnacci up to 32
It can go way higher but it didn't fit the screenshot

**Comment by fharookshaik** [comment]
Cool!
Thanks for your enormous contribution! Hope to see your future contributions to this project.

Happy Coding!!
Happy Contributing!!

Make a comment if it didn't accepted for the hacktoberfest.

**Pull request merged**
