### PR TITLE
created golang fibonacci series

### PR DESCRIPTION
**Pull request by Red-0111**

### CODE REVIEW

**Comment by fharookshaik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- GO_fibonacci.go  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6290461&bid=20465465)

**Comment by Red-0111** [comment]
please check added c++ and golang version

**Comment by fharookshaik** [comment]
Appreciated Your effort. But there's a code already developed in go language. Before making any changes read the instrustions carefully.

**Comment by fharookshaik** [comment]
You can update the existing code written in Go language.

**Pull request closed without merging**
